version: "3"

services:
    reverseproxy:
        build: ./proxy
        ports:
            - 8080:8080
        links:
            - web
            - app

    web:
        image: nginx
        volumes:
            - ./src:/usr/share/nginx/html

    app:
        build: ./App
        volumes:
            - ./App:/code
        depends_on:
            - redis

    redis:
        image: redis