version: "3"

services:
    reverseproxy:
        build: ./proxy
        ports:
            - 8080:8080
            - 5000:5000
        links:
            - client
            - web

    client:
        image: nginx
        volumes:
            - ./src:/usr/share/nginx/html

    web:
        build: .
        volumes:
            - .:/code
        depends_on:
            - redis

    redis:
        image: redis