version: "3"

services:
    reverseproxy:
        build: ./proxy
        ports:
            - 80:80
            - 5000:5000

    client:
        depends_on: 
            - reverseproxy
        image: nginx
        volumes:
            - ./src:/usr/share/nginx/html

    web:
        build: .
        volumes:
            - .:/code
        depends_on:
            - redis
            - reverseproxy

    redis:
        image: redis